### ISSUE TITLE
goreleaser/scoop

### ISSUE THREAD

**Issue by jlanzarotta** [shipengqi/commitizen#107]
### Is your feature request related to a problem? Please describe.

Is there any interest to implement [goreleaser](https://goreleaser.com/) to push a new version of commitizen to [scoop](https://scoop.sh/)?  The benefit of using scoop, is that when a new version of commitizen is created, scoop can be used to automatically update a local installation.

### Describe the solution you'd like

During the build process, goreleaser would push the newly built version to the scoop/extras bucket.  I am not 100% sure about pushing to scoop/extras, but pushing there would help from having to create a commitizen specific bucket.

### Search

- [X] I did search for other open and closed issues before opening this

**Comment by shipengqi** [comment]
Ok, thanks, I‘ll try it [Goreleaser Scoop Manifests](https://goreleaser.com/customization/scoop/).

**Comment by jlanzarotta** [comment]
Thanks.  It is not too difficult as I have implemented it for my Windows application.  Since you are offering other operating systems other than just Windows, it might be a bit of a challenge...

**Comment by shipengqi** [comment]
Done https://github.com/shipengqi/commitizen/pull/113 .
